### ISSUE TITLE
Would a W65C02S8P-10 work too?

### ISSUE THREAD

**Issue by AlecVoid** [TheByteAttic/Sally-to-W65C02S-adapter#1]
Hi,

the docs say that I should use a W65C02S6TPG-14 CPU but I wonder if a W65C02S8P-10 would work.

Regards,
Alex.

**Comment by AlecVoid** [comment]
Too bad that my issue was not answered. 

I used W65C02S8P-10 and it did NOT work (video signal but blank black screen). It might have been a counterfeit chip - I have no way to confirm it though.

**Comment by repetto74** [comment]
Hello,

Tried also to build this project using a W65C02S8P-10 from Aliexpress and no luck as you. Only difference is that I do get a screen filled with garbage in Graphics 2 mode (weird). I think either those CPU are fake or either they do not have the proper timing/speed required. Probably sourcing a good W65C02S6TPG-14 will fix it.

**Comment by goloskokovic** [comment]
W65C 02S 6T P G -14

**_Description_**: W65C
**_Product Identification Number_**: 02S
**_Foundry Process_**: 6T
6=.6u 1P/2M CMOS Process
T= TSMC Foundry
**_Package_**: P
P = Plastic Dual-In-Line, 40 pins
**_RoHS/Green Compliance_**: G
G = RoHS/Green Compliant (Wafer and Packaging)
**_Speed Designator_**: -14
14MHz

** RDY is a bidirectional pin on the W65C02S. Early W65C02S version has a low impedance pull up resistor. The latest W65C02S6T devices (wafers manufactured at TSMC) no longer have the internal pull-up on the RDY pin

https://www.westerndesigncenter.com/wdc/AN-002_W65C02S_Replacements.php

**Comment by repetto74** [comment]
Hello goloskokovic,
I have sourced a W65C02S6TPG-14 and all worked good :-). Thank you for your fix, I will try it with a couple of W65C02S6T I have in my stock and hopefully use them to build a couple more of this Sally replacement!

**Comment by goloskokovic** [comment]
Most W65C02S8P-10 on Aliexpress are actually resanded/repainted Rockwell 6502. They don't have BE on pin 36 but NC.
You could get good one but chances are 50-50%.

![fake](https://github.com/user-attachments/assets/45ab2f55-1039-491c-afa1-e8ded2f8ad0e)

**Comment by repetto74** [comment]
Ok understood now that your previous fix is for the Apple IIe :-). Well indeed could be that the W65C02S8P-10 is a fake chip. Anyway I got it working with a genuine W65C02S6TPG-14.
